### ISSUE TITLE
Changing background color in PDF

### ISSUE THREAD

**Issue by arielah** [vincerubinetti/svg-to-png#2]
When you unclick the box that says "transparent," in the preview the background color immediately goes to black. When you alter the background color using the little RGB popout and then click outside to close the popout, the background color on the preview does not change to match the new color. I clicked download and the background color was still black as well. 
![Screen Shot 2020-07-07 at 5 14 38 PM](https://user-images.githubusercontent.com/14189222/86844012-64055880-c075-11ea-98e4-7c0010f7b329.png)
![Screen Shot 2020-07-07 at 5 14 45 PM](https://user-images.githubusercontent.com/14189222/86844022-68ca0c80-c075-11ea-96bb-40ea50bbfa43.png)
![Screen Shot 2020-07-07 at 5 14 54 PM](https://user-images.githubusercontent.com/14189222/86844033-6b2c6680-c075-11ea-89ea-6af11cbbb659.png)

**Comment by vincerubinetti** [comment]
Just saw this now! Dont know why I'm not getting notifications for my own repos.

Have you tried the latest version? Background color seems to work for me. Also did you mean to say `svg` instead of `pdf`? Because I have no idea what would happen if you try to load a PDF, even though it is a vector format too.
